export const CLOTHING_CATEGORIES = [
    "top",
    "bottom",
    "shoes",
    "accessory",
    "outerwear",
] as const;

export type ClothingCategory = typeof CLOTHING_CATEGORIES[number];

export const SUBCATEGORIES: Record<ClothingCategory, string[]> = {
    top: [
        "t-shirt",
        "shirt",
        "blouse",
        "sweater",
        "hoodie",
        "tank top",
        "bodysuit",
        "corset",
        "vest",
        "polo",
        "turtleneck",
        "crop top",
        "sweatshirt",
        "camisole",
        "tube top",
    ],
    bottom: [
        "jeans",
        "pants",
        "shorts",
        "skirt",
        "leggings",
        "sweatpants",
        "trousers",
        "joggers",
        "cargo pants",
        "maxi skirt",
        "mini skirt",
        "chinos",
        "culottes",
    ],
    shoes: [
        "sneakers",
        "boots",
        "heels",
        "sandals",
        "flats",
        "loafers",
        "slippers",
        "oxfords",
        "wedges",
        "running shoes",
        "platforms",
    ],
    accessory: [
        "hat",
        "scarf",
        "gloves",
        "belt",
        "bag",
        "jewelry",
        "sunglasses",
        "tie",
        "beanie",
        "cap",
        "watch",
        "earrings",
        "necklace",
        "bracelet",
    ],
    outerwear: [
        "jacket",
        "coat",
        "blazer",
        "cardigan",
        "raincoat",
        "parka",
        "trench coat",
        "puffer jacket",
        "denim jacket",
        "leather jacket",
        "bomber jacket",
        "windbreaker",
    ],
};

// Flattened list of all subcategories for the DB Enum
export const ALL_SUBCATEGORIES = Object.values(SUBCATEGORIES).flat();
